[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"
deca-VampireCommandFramework = "0.10.2"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"

[publish.categories]
v-rising = ["oakveil-update", "mods", "server"]

[package]
namespace = "zfolmt"
name = "Bloodcraft"
versionNumber = "1.9.8"
description = "Leveling, expertise, legacies, professions, familiars, classes, quests!"
websiteUrl = "https://github.com/mfoltz/Bloodcraft"
containsNsfwContent = false
